GET http://localhost:3000/books

###
GET http://localhost:3000/books/3

###
POST http://localhost:3000/books
Content-Type: application/json


{
    "title":  "Machine learning with Python",
    "isbn": "4444-888-999",
    "publishedDate": "12/28/2009",
    "author": "John Smith"
}


###
DELETE http://localhost:3000/books/3

###
PUT http://localhost:3000/books/4
Content-Type: application/json

{
    "title":  "Advance Machine learning with Python",
    "isbn": "4444-888-999",
    "publishedDate": "12/28/2009",
    "author": "John Smith"
}